### ISSUE TITLE
Add path parameter to export actions

### ISSUE THREAD

**Issue by o01eg** [bend-n/godot-actions#1]
In some cases Godot project could be placed in non-root folder of repository. Would be useful to support `--path` argument for Godot export command.

**Comment by bend-n** [comment]
How would you like this to be supported?

Do you want it to be 
- a environment parameter
- a parameter to the composite action
- a github secret
- something else

?

**Comment by o01eg** [comment]
I think either environment parameter or action input is fine as I think it tends to be a static value for repository.

**Comment by bend-n** [comment]
@o01eg Does https://github.com/bend-n/godot-actions/commit/8931ec7cde50446a39d69cd6cb503b224699b7b7 work?

**Comment by o01eg** [comment]
Should work. I'll test it later.

**Comment by bend-n** [comment]
~~Not fixed, have to change the paths for the get name script, and gpm.~~ fixed!

**Comment by o01eg** [comment]
I suppose `export_presets.cfg` should be search in the same path.

**Comment by o01eg** [comment]
Looks like it fixed recently. I'll try it again but for release here still repository root used in: https://github.com/bend-n/godot-actions/blob/0b45a78251700138221637f808ff5f0ab4c91278/.github/actions/export-android/action.yml#L49
